#ifndef _AVALON_SGDMA_REGS_H_
#define _AVALON_SGDMA_REGS_H_

/*
 *  レジスタビット定義
 */

/* status レジスタ */

#define AVALON_SGDMA_STATUS_ERROR			UINT_C(0x01)
#define AVALON_SGDMA_STATUS_EOP_ENCOUNTERED		UINT_C(0x02)
#define AVALON_SGDMA_STATUS_DESC_COMPLETED		UINT_C(0x04)
#define AVALON_SGDMA_STATUS_CHAIN_COMPLETED		UINT_C(0x08)
#define AVALON_SGDMA_STATUS_BUSY			UINT_C(0x10)

/* control レジスタ */

#define AVALON_SGDMA_CONTROL_IE_ERROR			UINT_C(0x01)
#define AVALON_SGDMA_CONTROL_IE_EOP_ENCOUNTERED		UINT_C(0x02)
#define AVALON_SGDMA_CONTROL_IE_DESC_COMPLETED		UINT_C(0x04)
#define AVALON_SGDMA_CONTROL_IE_CHAIN_COMPLETED		UINT_C(0x08)
#define AVALON_SGDMA_CONTROL_IE_GLOBAL			UINT_C(0x10)
#define AVALON_SGDMA_CONTROL_RUN			UINT_C(0x20)
#define AVALON_SGDMA_CONTROL_STOP_DMA_ER		UINT_C(0x40)
#define AVALON_SGDMA_CONTROL_IE_MAX_DESC_PROCESSED	UINT_C(0x80)
#define AVALON_SGDMA_CONTROL_MAX_DESC_PROCESSED		UINT_C(0xff00)
#define AVALON_SGDMA_CONTROL_SOFTWARERESET		UINT_C(0X10000)
#define AVALON_SGDMA_CONTROL_PARK			UINT_C(0X20000)
#define AVALON_SGDMA_CONTROL_DESC_POLL_EN		UINT_C(0X40000)
#define AVALON_SGDMA_CONTROL_DESC_POLL_FREQ		UINT_C(0x7ff00000)
#define AVALON_SGDMA_CONTROL_CLEAR_INTERRUPT		UINT_C(0X80000000)

/*
 *  SGDMA レジスタ・マップ
 */

typedef struct t_sgdma_csr {
	uint32_t	status;
	uint32_t	status_pad[3];

	uint32_t	control;
	uint32_t	control_pad[3];

	uint32_t	next;
	uint32_t	next_pad[3];
	} T_SGDMA_CSR;

#endif	/* of #ifndef _AVALON_SGDMA_REGS_H_ */
